# Generated by Django 6.0.7 on 2026-08-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='The position of this question within its subject.', verbose_name='Question Number')),
                ('question_text', models.TextField(help_text='The question the learner will see.', verbose_name='Question Text')),
                ('option_a', models.CharField(help_text='The text for option A.', max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(help_text='The text for option B.', max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(help_text='The text for option C.', max_length=500, verbose_name='Option C')),
                ('option_d', models.CharField(help_text='The text for option D.', max_length=500, verbose_name='Option D')),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Select which option (A, B, C, or D) is the correct answer.', max_length=1, verbose_name='Correct Answer')),
                ('explanation', models.TextField(help_text='Detailed explanation of the concept and why the answer is correct.', verbose_name='Explanation')),
                ('python_code', models.TextField(blank=True, help_text='Multiline formatted Python code demonstrating the concept (optional).', verbose_name='Python Code')),
                ('practical_example', models.TextField(blank=True, help_text='A practical example that helps the learner understand the concept (optional).', verbose_name='Practical Example')),
                ('subject', models.ForeignKey(help_text='The subject this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['subject', 'question_number'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'question_number'), name='unique_question_number_per_subject')],
            },
        ),
    ]
