# Generated by Django 6.0.7 on 2026-08-01 07:39

from django.db import migrations


def seed_initial_subjects(apps, schema_editor):
    """
    Insert the 8 initial learning subjects into the database.
    This runs once when the migration is applied.
    """
    Subject = apps.get_model('core', 'Subject')

    subjects = [
        {'name': 'Python', 'slug': 'python', 'order': 1},
        {'name': 'NumPy', 'slug': 'numpy', 'order': 2},
        {'name': 'Pandas', 'slug': 'pandas', 'order': 3},
        {'name': 'Matplotlib', 'slug': 'matplotlib', 'order': 4},
        {'name': 'SciPy', 'slug': 'scipy', 'order': 5},
        {'name': 'Statistics', 'slug': 'statistics', 'order': 6},
        {'name': 'Linear Algebra', 'slug': 'linear-algebra', 'order': 7},
        {'name': 'Machine Learning', 'slug': 'machine-learning', 'order': 8},
    ]

    for item in subjects:
        Subject.objects.get_or_create(**item)


def remove_initial_subjects(apps, schema_editor):
    """
    Reverse the seeding: remove the 8 initial subjects.
    (Used if this migration is ever rolled back.)
    """
    Subject = apps.get_model('core', 'Subject')
    Subject.objects.filter(slug__in=[
        'python', 'numpy', 'pandas', 'matplotlib',
        'scipy', 'statistics', 'linear-algebra', 'machine-learning',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_initial_subjects, remove_initial_subjects),
    ]
