# Generated by Django 6.0.7 on 2026-08-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(help_text='The option (A, B, C, or D) the user selected.', max_length=1, verbose_name='Selected Answer')),
                ('is_correct', models.BooleanField(help_text='Whether the user selected the correct answer.', verbose_name='Is Correct')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, help_text='When the user submitted this answer.', verbose_name='Attempted At')),
                ('question', models.ForeignKey(help_text='The question that was answered.', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.question', verbose_name='Question')),
                ('user', models.ForeignKey(help_text='The user who answered this question.', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress Records',
                'ordering': ['user', 'question__subject', 'question__question_number'],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_progress')],
            },
        ),
    ]
