# Generated by Django 6.0.7 on 2026-08-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='The project title, e.g. "Titanic Survivor Prediction".',
                        max_length=200,
                        unique=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='URL-friendly name, e.g. "titanic-survivor-prediction".',
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="One or two sentences shown on the project card.",
                        max_length=300,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image shown on the project card.",
                        null=True,
                        upload_to="project_thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Markdown introduction shown on the project detail page.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True,
                        help_text="Markdown project overview. Shown after the MCQs are done.",
                        verbose_name="Overview",
                    ),
                ),
                (
                    "complete_code",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. The full project code with ```python code blocks.",
                        verbose_name="Complete Python Code",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. Formatted output, results, screenshots (later).",
                        verbose_name="Output / Results",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. Step-by-step explanation of the code and approach.",
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. What the learner will take away from this project.",
                        verbose_name="Learning Outcomes",
                    ),
                ),
                (
                    "dataset_info",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. Dataset description, source, and format (optional).",
                        verbose_name="Dataset Information",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Controls the order projects appear in.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this project from the public site.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=True,
                        help_text="Future monetization: whether this project is free.",
                        verbose_name="Is Free",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("paid", "Paid"),
                        ],
                        default="free",
                        help_text="Future monetization: free / premium / paid.",
                        max_length=20,
                        verbose_name="Access Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "title"],
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["question_number"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.RemoveConstraint(
            model_name="question",
            name="unique_question_number_per_subject",
        ),
        migrations.AlterField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="The subject this question belongs to. Leave empty if the question belongs to a Project.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="The project this question belongs to. Leave empty if the question belongs to a Subject.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.project",
                verbose_name="Project",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("project__isnull", True), ("subject__isnull", False)),
                    models.Q(("project__isnull", False), ("subject__isnull", True)),
                    _connector="OR",
                ),
                name="question_belongs_to_subject_or_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subject__isnull", False)),
                fields=("subject", "question_number"),
                name="unique_question_number_per_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("project", "question_number"),
                name="unique_question_number_per_project",
            ),
        ),
    ]
