# Generated by Django 6.0.7 on 2026-08-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_alter_question_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text='The broader module, e.g. "Pandas".',
                        max_length=100,
                        verbose_name="Module",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text='The topic of this lesson, e.g. "Filtering & GroupBy".',
                        max_length=200,
                        verbose_name="Topic",
                    ),
                ),
                (
                    "lesson_slug",
                    models.SlugField(
                        help_text='URL-friendly lesson identifier, e.g. "pandas-filtering-sorting-groupby-aggregation".',
                        max_length=200,
                        unique=True,
                        verbose_name="Lesson Slug",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Coding Lesson",
                "verbose_name_plural": "Coding Lessons",
                "ordering": ["module", "topic"],
            },
        ),
        migrations.CreateModel(
            name="CodingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_number",
                    models.PositiveIntegerField(
                        help_text="The position of this exercise within its lesson.",
                        verbose_name="Exercise Number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short, descriptive title for the exercise.",
                        max_length=300,
                        verbose_name="Title",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        help_text="e.g. beginner / intermediate / advanced.",
                        max_length=50,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "estimated_time",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Approximate time to complete, in minutes.",
                        verbose_name="Estimated Time (minutes)",
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. What the learner should achieve.",
                        verbose_name="Objective",
                    ),
                ),
                (
                    "ml_connection",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. How this connects to machine learning (optional).",
                        verbose_name="ML Connection",
                    ),
                ),
                (
                    "dataset_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the dataset used (optional).",
                        max_length=200,
                        verbose_name="Dataset Name",
                    ),
                ),
                (
                    "dataset_description",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. Description of the dataset (optional).",
                        verbose_name="Dataset Description",
                    ),
                ),
                (
                    "dataset_preview",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional preview rows of the dataset (JSON).",
                        verbose_name="Dataset Preview",
                    ),
                ),
                (
                    "problem_statement",
                    models.TextField(
                        help_text="Markdown. The problem the learner must solve.",
                        verbose_name="Problem Statement",
                    ),
                ),
                (
                    "starter_code",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. Initial code the learner starts from (```python).",
                        verbose_name="Starter Code",
                    ),
                ),
                (
                    "expected_solution",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. A reference solution (```python).",
                        verbose_name="Expected Solution",
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. The expected output of a correct solution.",
                        verbose_name="Expected Output",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Markdown. Step-by-step explanation of the solution.",
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "common_mistakes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional list of common mistakes (JSON).",
                        verbose_name="Common Mistakes",
                    ),
                ),
                (
                    "hints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional list of hints (JSON).",
                        verbose_name="Hints",
                    ),
                ),
                (
                    "concepts_covered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional list of concepts covered (JSON).",
                        verbose_name="Concepts Covered",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="The coding lesson this exercise belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="core.codinglesson",
                        verbose_name="Lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coding Exercise",
                "verbose_name_plural": "Coding Exercises",
                "ordering": ["lesson", "exercise_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lesson", "exercise_number"),
                        name="unique_exercise_number_per_lesson",
                    )
                ],
            },
        ),
    ]
