# Generated by Django 6.0.7 on 2026-08-06 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_codinglesson_codingexercise"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="codinglesson",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link this coding lesson to a subject so it appears in that subject's learning flow.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coding_lessons",
                to="core.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.CreateModel(
            name="CodingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user marked this exercise as complete.",
                        verbose_name="Is Completed",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the user completed this exercise.",
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        help_text="The coding exercise that was completed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="core.codingexercise",
                        verbose_name="Exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who completed this coding exercise.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coding Progress",
                "verbose_name_plural": "Coding Progress Records",
                "ordering": ["user", "exercise__lesson", "exercise__exercise_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "exercise"),
                        name="unique_user_exercise_progress",
                    )
                ],
            },
        ),
    ]
